print ("Bienvenido al programa, que calcula el procentaje de inversión total")
print ("********************************************************************")
inver1=str(input("Digite el nombre del primer inversionista: "))
inver1Valor=int(input("Digite el valor a invertir: "))
inver2=str(input("Digite el nombre del segundo inversionista: "))
inver2Valor=int(input("Digite el valor a invertir: "))
inver3=str(input("Digite el nombre del tercer inversionista: "))
inver3Valor=int(input("Digite el valor a invertir: "))
inver4=str(input("Digite el nombre del cuarto inversionista: "))
inver4Valor=int(input("Digite el valor a invertir: "))
totalInversion=int(inver1Valor+inver2Valor+inver3Valor+inver4Valor)
porcenInv1=float((inver1Valor*100)/totalInversion)
porcenInv2=float((inver2Valor*100)/totalInversion)
porcenInv3=float((inver3Valor*100)/totalInversion)
porcenInv4=float((inver4Valor*100)/totalInversion)
print ("La inversión Total del proyecto es de: $",totalInversion)
print ("La inversión de:",inver1,"es: $",inver1Valor,"y corresponde al",porcenInv1,"%")
print ("La inversión de:",inver2,"es: $",inver2Valor,"y corresponde al",porcenInv2,"%")
print ("La inversión de:",inver3,"es: $",inver3Valor,"y corresponde al",porcenInv3,"%")
print ("La inversión de:",inver4,"es: $",inver4Valor,"y corresponde al",porcenInv4,"%")