print ("Bienvenido al programa, que convierte de grados Celsius a Faharenheit")
print ("********************************************************************")
celsius=int(input ("Por favor escriba la temperatura en ºC que desea convertir a ºF:"))
farhenheit=float(((celsius*9)/5)+32)
print ("El resultado de convertir", celsius,"ºC a Farhenheit es:",farhenheit,"ºF")